### ISSUE TITLE
Upload progress UI

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-upload#15]
There should be a nice UI for the reading and uploading images in the CKEditor 5. It should handle 2 cases:

## Case 1: I'm uploading a small image (1MB with SSD drive)

I this case the user will see the placeholder for the very short time (less than half of the second). The image will load quickly and upload start sooner than user notice that there was a reading step. In this case, we want to avoid showing a big and dark placeholder, what will look like a strange blinking, breaking the feeling of the smooth image uploading.

## Case 2: I'm uploading a big image (5 MB with HDD drive)

I this case the reading process take some time (more-less 3 seconds). We need to show the user something for these 3 seconds because if there will be no reaction after he pasted, dropped or selected the image he will have a feeling that something is broken. We need to show him some kind of a placeholder.

**Comment by SteveTheTechie** [comment]
Please excuse me for butting in, but have you considered maybe using an animated pie progress counter as part of your place holder?   Because this sort of progress counter is circular (as opposed to a typical progress bar), it should be compatible with a wide variety of image aspect ratios.  Besides, it looks cool, and is easy to do.   I found the following via Google as an example:  [https://codepen.io/DeptofJeffAyer/pen/ogPbPG](url)

**Comment by szymonkups** [comment]
Hi @SteveTheTechie, 
In the first implementation that I am currently working on we are using different approach. We have two upload phases: reading from disk and uploading. Placeholder is only visible for the first phase ( espacially in case 2 described by @pjasiun), then read image is displayed until it's uploaded. We don't want to cover it by progress indicator, so we decided that small progress bar on top of the image would be the best way to go (it is still WIP):

![output](https://cloud.githubusercontent.com/assets/2396463/25265091/769e7500-266b-11e7-9604-8d522816ebc9.gif)

On the other hand - we are trying to implement it in the way that will be possible to customize upload progress displayed on the image and It would be great to see if other approaches are easily implementable too.

**Comment by pjasiun** [comment]
@SteveTheTechie, at the same time you can check out these mock-ups, which we are considering implementing in the future: https://github.com/ckeditor/ckeditor5-image/issues/16#issuecomment-279640113
