### ISSUE TITLE
Image balloon panel in wrong position during upload

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-upload#20]
![output](https://cloud.githubusercontent.com/assets/2396463/25327313/f6147ce8-28d3-11e7-90bf-a077516ffee9.gif)

I'm reporting this here but it might be a problem to fix in `ckeditor5-image` - needs some investigation.

**Comment by oleq** [comment]
I stumbled upon this today and yes, I also suspect the problem is in `ckeditor5-image` and https://github.com/ckeditor/ckeditor5-image/issues/96 should help a lot.

**Comment by Mgsy** [comment]
I'm not able to reproduce it. Guys, could I ask you to confirm that this one is fixed?
