### ISSUE TITLE
Editor has no focus after drop

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-upload#24]
This TC may be only reproducible on macOS. Make sure to click on the desktop (to blur the browser) before DnDing the file.

![may-08-2017 11-29-40](https://cloud.githubusercontent.com/assets/156149/25798489/aed9f7b8-33e1-11e7-9f95-3896219a9d22.gif)

I can see that in CKE4 there's no focus too... it stays in the desktop (or in the Finder). I hope we can do something about it.

**Comment by Reinmar** [comment]
I left it as a "status:discussion" cause I'm not 100% sure we should actually try to "steal" the focus (if the OS didn't give it to us).

Also, perhaps we can improve it differently. It was confusing for me because the image had border and because I had to click it twice. I don't know. Something there was not right.

**Comment by pjasiun** [comment]
We should check how it works for other applications.

**Comment by mlewand** [comment]
I gave it a quick spin and I can see that Safari does not focus the browser when dropping image.

In that case I highly doubt it will allow to bring focus to the window as it would pose a great potential for abusing the end-user.

That being said I don't think this is an important issue, confirmed by the fact that there has been no response from community on that for more than 2 years.
