### ISSUE TITLE
The progress is invisible and lacks "success" indication

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-upload#25]
I had a totally "what's going on?!" reaction when I pasted the first file into the editor. I didn't know before how it's supposed to work so it was quite genuine.

First of all, the progress bar is small and nearly overlaps with the image border (sorry for dropping a CKE screenshot, that doesn't help reading the outer screenshot :D):

![image](https://cloud.githubusercontent.com/assets/156149/25798853/10278e80-33e3-11e7-9dbf-9fd5a3a43d6f.png)

When I've been dropping some files with a more blueish background (e.g. sky) it was totally invisible for me. So, I'd make it slightly bigger and/or drop some shadow.

Second of all, after the image is uploaded it would be nice if the success was indicated somehow. The lightest option is to make the progress green for a while and blink it somehow (like "ding!") and then hide. Some CSS animation would most likely be fully sufficient.

**Comment by Reinmar** [comment]
Note: The success notification is especially important in a case of dropping small files. I could barely see the progress bar in those cases and then I didn't know if the file was uploaded or not... I was honestly confused, even though I know more or less what should happen.

Also, since the progress may sometimes be nearly invisible, perhaps after the image is uploaded, entire image should be used for the "ding!" stuff.

**Comment by Reinmar** [comment]
Find the progress bar:

![image](https://cloud.githubusercontent.com/assets/156149/25799070/ebfccae2-33e3-11e7-8faf-10c8c1cdd2ef.png)

**Comment by fredck** [comment]
Part of what you're asking here goes a bit against what we were, in fact, trying to achieve: a seamless user experience, without the technicities. One just drops the image and it is there like expected. Therefore, "confirmations" are not necessary.

I understand that you're a developer and that you're in fact "testing" the upload thing, so you have your doubts if this really works. But let's give priority to the end user, who doesn't care/know about all this technical stuff and just want the image there. So, if it is there after drop, the assumption is that everything is fine.

**Comment by Reinmar** [comment]
I've not been testing the upload thing, I've been actually using it. And I got confused.

I understand that developers have a certain way of looking at the UX aspects but blaming everyone for being a developer makes no sense (sorry, but that's how your comment sounds to me – it discredits my experience just because I happen to me a developer). You're a developer too. How do you know that you're right? How do you know that "a seamless user experience, without the technicities" isn't just like trying to fake desktop experience in the web? How do you know that you haven't got too far in the search for "non dev UX"? None of the extremes is good.

Besides, really, in all webapps and websites I know the upload process is visible. That's why this was confusing to me – I've been actually expecting something to happen because it always happens. There are some patterns out there and we need to be extremely careful when leaving the well-known path.

**Comment by fredck** [comment]
That's definitely the way of developers to see things, in my sincere opinion.

One example of this is Medium... no progress bars whatsoever. If I drop the image, it is just there. I don't have to worry because, as a matter of fact, it must just work. And I see my image in place, just like I expected. What could be more clear as "success" result?! I don't need UI just so I can trust the application to do its job.

**Comment by Reinmar** [comment]
> Besides, really, in all webapps and websites I know the upload process is visible. That's why this was confusing to me – I've been actually expecting something to happen because it always happens. There are some patterns out there and we need to be extremely careful when leaving the well-known path.

I've decided to check it again and I need to correct myself. While e.g. GH, Gmail, FB display the progress GDrive and Twitter and Medium do not. So, in half of the cases there's no feedback. 

So, I wonder why I was confused by CKEditor 5. Maybe, it's because there's some feedback (some small progress), but it's not clear and consequent. Because it lacks some closure? Maybe, if we say A we should say B, so if there's progress bar it should be more clear?

**Comment by Reinmar** [comment]
In other words – perhaps the way to go is to not have any progress/status indication or a complete, clear indication.

When making a decision we should take use cases in mind. For example, Medium is a closed system, while CKEditor is often embedded in various places (see https://github.com/ckeditor/ckeditor5-upload/issues/26).

**Comment by mlewand** [comment]
Note that this feature has changed a little over the time. Now we have a clear success indication (green checkmark). I agree that progress bar is virtually invisible unless you know that it's there, that was a reason to implement it [thicker in CKE4 EasyImage](https://ckeditor.com/docs/ckeditor4/latest/examples/easyimage.html) - so that there's a gentle feedback on upload process.

**Comment by Reinmar** [comment]
I agree. I think it's fine now.
