### ISSUE TITLE
How can a developer block/sync a form before all uploads finish?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-upload#26]
It'd be good to make it clear how to sync the form (or the app in which CKEditor is embedded) with the upload. We need an API and some proposals because blocking a form is just one of the options.

------

If you'd like to see this feature implemented, add 👍 to this post.

**Comment by pjasiun** [comment]
For now, it's only possible to check if there are pending uploads:
```js
editor.plugins.get( 'upload/filerepository' ).loaders.length
```

**Comment by Reinmar** [comment]
What are "pending uploads"? Started uploads in progress?

**Comment by pjasiun** [comment]
Yep.

**Comment by mlewand** [comment]
This also should be reflected in the docs.

**Comment by Reinmar** [comment]
This is actually covered in https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html#handling-users-exiting-the-page
