### ISSUE TITLE
[Safari, Edge] Image upload doesn't work on Safari and Edge

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-upload#35]
## Steps to reproduce
1. Open a sample with the image upload plugin.
2. Try to insert some image.

## Current result
The image was not inserted and there is an error in browser's console.

## Logs
Error on Edge - https://gist.github.com/Mgsy/e7e32b829d0673cf3e0492b7cbaf8234
Error on Safari - https://gist.github.com/Mgsy/d292f0f75867cb3cf83c644417949112

## Other information
OS: Windows 10, MacOS X
Browser: Edge, Safari
Release: 0.10.0

**Comment by Reinmar** [comment]
Error in Safari:

![image](https://user-images.githubusercontent.com/156149/27402868-87a34dde-56c8-11e7-8c3a-ddf0d127fee5.png)

Sounds like Safari still doesn't support the iterator interface on file list.

@Mgsy – could you check that Edge 15 has still the same problem? They implemented the iterable interface on NodeList and similar objects.

**Comment by Mgsy** [comment]
@Reinmar, yes - Edge 15 throws an error too. Here it is:
`SCRIPT438: Object doesn't support property or method 'Symbol.iterator'`
`emittermixin.js (577,1)`

**Comment by Reinmar** [comment]
Adding to iteration 11 as this will be a simple fix (most likely) – we shouldn't use the `for of`  loop on this object.
