### ISSUE TITLE
Chrome warns about new lines in attributes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-upload#37]
When I drop an image Chrome shows the following warning:

> [Deprecation] Resource requests whose URLs contain raw newline characters are deprecated, and may be blocked in M60, around August 2017. Please remove newlines from places like element attribute values in order to continue loading those resources. See https://www.chromestatus.com/features/5735596811091968 for more details.

**Comment by karuppasamy20** [comment]
You have to do replace the newline character in string after that it will be solve.

String.replace(/\n|\r/g, "");

**Comment by pomek** [comment]
I cannot reproduce this issue…

**Comment by Mgsy** [comment]
I'm not able to reproduce it neither.

**Comment by wwalc** [comment]
Maybe the file that @Reinmar tried had a space in its name?
