### ISSUE TITLE
Upload multiple images at the same time

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-upload#6]
It should be possible to insert multiple images. They should appear one after another. This should be tests and fix if needed.

**Comment by szymonkups** [comment]
Error is shown when one image is selected and we want to insert another one, this should be fixed.
![image](https://cloud.githubusercontent.com/assets/2396463/25004914/eea24c40-2056-11e7-9758-ab0474bf7490.png)
