### ISSUE TITLE
Fix CSS class names

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-upload#65]
As @oleq pointed out in [this comment](https://github.com/ckeditor/ckeditor5-upload/pull/64#discussion_r142112012), CSS class names should be compliant with [our Naming Guidelines](https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines#css-classes).

**Comment by Reinmar** [comment]
I assume it's done. cc @oleq @dkonopka
