### ISSUE TITLE
Editor with upload plugin throws an error when destroy is called more than once

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-upload#66]
This is because `FileDialogButtonView#destroy` tries to remove already removed file element from body

https://github.com/ckeditor/ckeditor5-upload/blob/811d32f1f95771cfd421723096d6265ca7ceb8b5/src/ui/filedialogbuttonview.js#L81

Replacing
```javascript
document.body.removeChild( this.fileInputView.element )
```
by
```javascript
this.fileInputView.element.remove()
```
should help.

**Comment by oskarwrobel** [comment]
The problem is that `this.fileInputView` is not registered as a `FileDialogButtonView` child.

**Comment by oskarwrobel** [comment]
I'm wondering if `FileDialogButtonView`  should add its child view element somewhere to the `document.body` by its own or this should be done by the controller and this child view should be added to the `editor.ui.view.body` collection?

//cc @oleq

**Comment by oleq** [comment]
I think you're right but I'm not sure the solution is correct. 

The UI component should not work beyond the boundaries of its own `#element`. Otherwise, we're in troubles when implementing an editor in the [shadow DOM](https://github.com/ckeditor/ckeditor5-engine/issues/692). Is it possible for `FileDialogButtonView` to append the hidden input to its own `#element`?

**Comment by oskarwrobel** [comment]
> Is it possible for FileDialogButtonView to append the hidden input to its own #element?

I think it is possible but I'm not sure if it is correct to append input element to the button element.

**Comment by oskarwrobel** [comment]
MDN says that permitted content for `button` element is a [Phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) and `<input>` is on that list.

**Comment by oleq** [comment]
I guess not
![image](https://user-images.githubusercontent.com/1099479/31340513-ac6ce938-ad06-11e7-8309-e5a56ea073f2.png)
I think we're facing a bigger problem here and with the current architecture, `ImageUploadButton` should indeed make sure the hidden input lands in the "body" collection of the root view.

**Comment by oskarwrobel** [comment]
Yep, I checked the same
![image](https://user-images.githubusercontent.com/1057056/31340582-ea38a842-ad06-11e7-9703-1be46697bf10.png)

**Comment by oleq** [comment]
OTOH, we could create a component called `FileDialogButtonView`, which renders to
`<span><ButtonView><input type="hidden" /></span>`. WDYT?

**Comment by oskarwrobel** [comment]
We can append this view to the body collection in UploadButton controller

https://github.com/ckeditor/ckeditor5-upload/blob/811d32f1f95771cfd421723096d6265ca7ceb8b5/src/imageuploadbutton.js#L38-L63

by adding

```javascript
editor.ui.view.body.add( view.fileInputView );
```

**Comment by oskarwrobel** [comment]
> OTOH, we could create a component called FileDialogButtonView, which renders to
<span><ButtonView><input type="hidden" /></span>. WDYT?

Let's try.

**Comment by oleq** [comment]
I think sooner or later the `FileDialogButtonView` will become a common component in ckeditor5-ui. And then we'll face the problem again, so I wouldn't start with hacks ;-)
