### ISSUE TITLE
Image instead of text when pasting from Word

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-upload#68]
As described in this issue: https://github.com/ckeditor/ckeditor5/issues/653.

A simple fix for now will give higher priority to HTML in DataTransfer and use it instead of just taking all images from it and start uploading.

**Comment by export-mike** [comment]
paste from word doesn't seem to preserve html tables. :(

**Comment by Reinmar** [comment]
Paste from Word isn't yet supported. And there's no support for tables too. Both things are our greatest priority right now. You can already [follow the works on the table feature](https://github.com/ckeditor/ckeditor5-table/issues/1).

**Comment by export-mike** [comment]
:(

**Comment by tomaszhlawiczka** [comment]
Is it possible to force the editor to upload images when pasting them from the internet (like copied from the browser)?

![screenshot_20180720_231933](https://user-images.githubusercontent.com/19405886/43025742-3a4fbefa-8c73-11e8-88e8-be56843cfe0e.png)

So far, function `isHtmlIncluded()` prevents such insertion - the original URL of an image is used instead.

**Comment by pjasiun** [comment]
See https://github.com/ckeditor/ckeditor5-easy-image/issues/14. Please do ask such questions in tickets about another topic. Report a separate ticket in such cases.
