### ISSUE TITLE
Improve error when there is no-adapter

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-upload#8]
Note that this will be the most popular error the user will meet working with upload, most probably the first thing they will see after installing any upload plugin.

First, after experience with 4.5.0/4.5.1 release, there should not be an exception when there is no adapter. Instead, there should we a warning in the console and editor should keep working, even if upload is not possible.

Second, the message should be nice. It would be perfect if it would link to the guild how to add an adapter or to an existing adapter plugin, so the user will know how to enable upload.

**Comment by pjasiun** [comment]
Now if there is no adapter you can try to upload but the editor will crash as soon as you try. 

Instead, we could abort the upload or disable uploading command. Of course, there should be a message in the console anyway.

**Comment by Reinmar** [comment]
I reported a DUP in https://github.com/ckeditor/ckeditor5-upload/issues/23. Please also read it before starting to work on this ticket.

**Comment by Reinmar** [comment]
I improved the error significantly:

![image](https://user-images.githubusercontent.com/156149/31011869-20409f0c-a510-11e7-8da8-9173a0f44a46.png)

And it's going to be logged nicely and clearly:

![image](https://user-images.githubusercontent.com/156149/31011906-34955f74-a510-11e7-8f61-f86365d033a7.png)
