### ISSUE TITLE
[SimpleUploadAdapter] Consider responsive images in server response

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-upload#97]
ATM the adapter allows only a single `url` in the response from the server. This makes implementing responsive images impossible using the adapter. Let's consider allowing multiple URLs to different image sizes in the server response.

**Comment by Reinmar** [comment]
Definitely 👍 . The EasyImage service supports responsive images already, so all the things are there in place also on CKE5 side. In fact, what will we have to change in SUA itself to enable that? Sounds like a micro change.

**Comment by oleq** [comment]
1. Change the required server response format (docs, code) from:
   ```
   {
       url: 'http://example.com/images/image–default-size.png',
   }
   ```
   to
   ```
   {
       default: 'http://example.com/images/image–default-size.png',
       '160': 'http://example.com/images/image–size-160.image.png',
       '500': 'http://example.com/images/image–size-500.image.png',
       '1000': 'http://example.com/images/image–size-1000.image.png',
       '1052': 'http://example.com/images/image–default-size.png'
   }
   ```
2. Change the following line https://github.com/ckeditor/ckeditor5-upload/blob/master/src/adapters/simpleuploadadapter.js#L179-L181 to `resolve( response.urls );`
3. Update docs.

**Comment by Reinmar** [comment]
How do EI and CKF work? One of them uses responsive images, the other doesn't. Couldn't simple upload adapter support both cases?

**Comment by Reinmar** [comment]
OK, stupid question. You linked to the docs. 

So, I'm fine with both options:

* supporting both schemes (e.g. having such a normalisation: `data.url ? { default: data.url } : data.urls`)
* or supporting just the latter.
